# PalEON Summer Course: Forward model module
## August 2014
## Chris Paciorek


In this module, we'll do some hands-on work to simulate data from a model. 

# Practice with joint distributions

The values in `drawsOak.csv` are 250 draws from a multivariate distribution (we'll tell you what they actually are after we do the Bayes module). In this case, these are the estimated composition of oak at two nearby locations in Massachusetts based on Paciorek & McLachlan (2009). The first column is location 1 in 1750, the second column location 2 in 1750 and the third column location 1 in 1850. 

Do the following calculations:

  1. Using these draws as a representative sample from the underlying distribution, make plots and calculate summary statistics that estimate the marginal distributions of each of the three variables. 
  2. Next illustrate the bivariate relationship between the oak composition variables. 
  3. Next estimate the mean difference between the oak composition at the two locations in 1750, the standard deviation of that difference, and a 95% interval (2.5 to 97.5th percentiles of the draws). Consider whether two 95% intervals for the two oak variables computed separately seem to tell a different story than the 95% interval for the difference. 

# Simulation for a state space model

A core model used in statistics for time series data is called a dynamic linear model (versions of this are also known as a hidden Markov model or a state space model). Here's a basic model that one might use for binomial data, such as pollen data for a single taxon, where $\mbox{logit}(\theta) = \log(\frac{\theta}{(1-\theta)})$:

$$ 
\mbox{logit}(\theta_t)  \sim  N(\mbox{logit}(\theta_{t-1}), \tau^2)
$$
$$
y_{t}  \sim  \mbox{Binom}(n_{t},\theta_{t}).
$$


Let's work on the following:

  1. Write a function that simulates a single time series of data and hidden states using the model above. Determine what arguments your function will need.
  2. Simulate many random time series using your function; plot the hidden states (as connected lines) for multiple time series to illustrate the behavior of the model. Use $tau=0.2$ and $\theta_0 = 0.2$ for simplicity.
  3. Now let's do a very basic data assimilation. Using a large number of hidden state time series from part (b), calculate the log-likelihood of a time series of data that I will give you. The likelihood values (not on the log scale) are used to weight the hidden state time series (normalize these by the sum of the likelihood values across all the draws). Plot the hidden state series with the largest weights (we'll discuss how many to use), indicating the magnitude of the normalized weights somehow on the plot. Overlay the data. Congratulations, you've done a state variable data assimilation!
