# PalEON Summer Course: Practice with R
## August 2014
## Chris Paciorek

Here we'll do some analysis of the relationship of pollen and trees.
 This will involve some manipulation of data in R as well as graphics.
 Share tips amongst yourselves and let us know with questions or if you're
 looking for particular functionality.
 We'll try to compile a list of useful functions/tips on the board.

### Settlement pollen and calibration against vegetation

  1. Read the upper Midwest settlement-era pollen data (settlementPollen.csv) and PLS composition data (pls.csv)
 into R from the data/upperMidwest folder. Create an R data frame that contains
the pond-level information, as in the pondInfo.csv file in the New England data.

  2. Make some maps to see where the locations are and make some plots to assess
 the overall composition of different taxa in pollen and on the landscape.

  3. Match PLS data with each pond, either based on the nearest PLS grid cell
 to each pond or using all PLS data within some buffer (or some other strategy
 that you might come up with). The `rdist()` and `which.min()` functions
may come in handy. `rdist()` requires you load the *fields* package.

  4. Assess the relationship between pollen and PLS cells based on the proportions.
 
### Interpreting the proxy data as a record of the past

  5. Read in the pollen time series data for the upper Midwest (pollenTimeSeries.csv). Extract the data for Glimmerglass Lake and make some plots to assess how composition has changed over time.

  6. Try to assess whether nearby sites show similar temporal patterns.
 
  7. If you have a chance and can figure out how to do it, use the `gam()` function
 to smooth the time series, treating a single taxon as binomial data relative
 to all other taxa. You'll want to use "family = 'binomial'". 

[[[ Glimmer shows 6k increase in Tsuga and then decline; what about Tower re: Tsuga and Fagus? check with JWW/STJ on what events to focus on wrt interpreting output of stat model; as fall back see if Tsuga rise (to 15 count) and decline seems robust]]]
